title: "BSides Badge Writeup"
description: "CTF walkthrough and hardware reverse engineering of BSides Kristiansand 2025 badge"
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
